# Generated by Django 4.2.13 on 2024-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirm_password',
            field=models.CharField(default='exit', max_length=128),
            preserve_default=False,
        ),
    ]
